name: 'Run golangci-lint with reviewdog'
description: '🐶 Run golangci-lint with reviewdog on pull requests to improve code review experience.'
author: 'haya14busa (reviewdog)'
inputs:
  github_token:
    description: 'GITHUB_TOKEN.'
    required: true
    default: ${{ github.token }}
  golangci_lint_flags:
    description: 'golangci-lint flags. (golangci-lint run --out-format=line-number <golangci_lint_flags>)'
    default: ''
  skip-pkg-cache:
    description: "if set to true then the action don't cache or restore ~/go/pkg."
    default: 'false'
    required: 'true'
  skip-build-cache:
    description: "if set to true then the action don't cache or restore ~/.cache/go-build."
    default: 'false'
    required: 'true'
  tool_name:
    description: 'Tool name to use for reviewdog reporter'
    default: 'golangci'
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
  reporter:
    description: 'Reporter of reviewdog command [github-pr-check,github-pr-review,github-check].'
    default: 'github-pr-check'
  filter_mode:
    description: |
      Filtering for the reviewdog command [added,diff_context,file,nofilter].
      Default is added.
    default: 'added'
  fail_on_error:
    description: |
      Exit code for reviewdog when errors are found [true,false]
      Default is `false`.
    default: 'false'
  reviewdog_flags:
    description: 'Additional reviewdog flags'
    default: ''
  workdir:
    description: 'Working directory relative to the root directory.'
    default: '.'
runs:
  using: 'composite'
  steps:
    - uses: actions/cache@v2
      with:
        path: ~/.cache/golangci-lint
        key: ${{ runner.os }}-golangcilint-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-golangci-lint-

    - uses: actions/cache@v2
      if: ${{ inputs.skip-build-cache == 'false' }}
      with:
        path: ~/.cache/go-build
        key: ${{ runner.os }}-gobuild-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-gobuild-

    - uses: actions/cache@v2
      if: ${{ inputs.skip-pkg-cache == 'false' }}
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - run: $GITHUB_ACTION_PATH/script.sh
      shell: bash
      env:
        # We may want to allow specifing reviewdog and golangci-lint version as
        # action's input, but let's start with hard coded latest stable version.
        REVIEWDOG_VERSION: v0.11.0
        GOLANGCI_LINT_VERSION: v1.39.0
        # INPUT_<VARIABLE_NAME> is not available in Composite run steps
        # https://github.community/t/input-variable-name-is-not-available-in-composite-run-steps/127611
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_GOLANGCI_LINT_FLAGS: ${{ inputs.golangci_lint_flags }}
        INPUT_TOOL_NAME: ${{ inputs.tool_name }}
        INPUT_LEVEL: ${{ inputs.level }}
        INPUT_REPORTER: ${{ inputs.reporter }}
        INPUT_FILTER_MODE: ${{ inputs.filter_mode }}
        INPUT_FAIL_ON_ERROR: ${{ inputs.fail_on_error }}
        INPUT_REVIEWDOG_FLAGS: ${{ inputs.reviewdog_flags }}
        INPUT_WORKDIR: ${{ inputs.workdir }}
branding:
  icon: 'check-circle'
  color: 'blue'
